"""
Every genre spotify will accept as a seed genre for their recommendations API
"""

# buckets are highly experimental watch out

misc = [
    "afrobeat",
    "ambient",
    "anime",
    "blues",
    "bossanova",
    "brazil",
    "british",
    "children",
    "classical",
    "comedy",
    "disney",
    "forro",
    "french",
    "german",
    "gospel",
    "goth",
    "happy",
    "holidays",
    "honky-tonk",
    "idm",
    "indian",
    "iranian",
    "j-idol",
    "jazz",
    "kids",
    "latin",
    "latino",
    "malay",
    "movies",
    "mpb",
    "new-release",
    "opera",
    "pagode",
    "philippines-opm",
    "piano",
    "rainy-day",
    "road-trip",
    "romance",
    "sad",
    "salsa",
    "samba",
    "sertanejo",
    "show-tunes",
    "sleep",
    "soul",
    "soundtracks",
    "spanish",
    "study",
    "summer",
    "swedish",
    "tango",
    "turkish",
    "world-music"
  ]

beat = [
    "reggae",
    "reggaeton",
    "trip-hop",
    "r-n-b",
    "drum-and-bass",
    "chill",
    "hip-hop",
    "funk",
    "dancehall",
]

electronic = [
    "techno",
    "trance",
    "post-dubstep",
    "progressive-house",
    "new-age",
    "party",
    "hardstyle",
    "dub",
    "dubstep",
    "edm",
    "chicago-house",
    "minimal-techno",
    "j-dance",
    "dance",
    "club",
    "breakbeat",
    "electro",
    "electronic",
    "disco",
    "deep-house",
    "detroit-techno",
    "house",
]

pops = [
    "synth-pop",
    "singer-songwriter",
    "songwriter",
    "power-pop",
    "pop",
    "pop-film",
    "indie",
    "indie-pop",
    "k-pop",
    "j-pop",
    "mandopop",
    "cantopop",
    "garage",
    "folk",
    "acoustic",
]

metals = [
    "black-metal",
    "metalcore",
    "metal",
    "metal-misc",
    "heavy-metal",
    "death-metal",
    "hardcore",
    "grindcore",
    "industrial"
]

rocks = [
    "alternative",
    "rock",
    "alt-rock",
    "rock-n-roll",
    "rockabilly",
    "punk",
    "punk-rock",
    "j-rock",
    "emo",
    "hard-rock",
    "groove",
    "grunge",
    "guitar",
    "ska",
    "psych-rock",
    "work-out",
    "singer-songwriter",
    "songwriter",
    "industrial",
    "country",
    "garage",
    "acoustic",
    "bluegrass",
]
